### PR TITLE
Let's take this library up to 10.

### PR DESCRIPTION
**Pull request by brianegan**
Hey hey :) Cool library, thanks for making it available!

I needed some memoize functions, but was hoping to support the full range of `Func1-Func10`. Therefore, I needed memoizing functions that could handle that range, and figured I'd contribute to this lib since it's already out there :)

Changes:

  - Added memo5-memo10 & imemo5-imemo10
  - Added tests for these new functions
  - Updated readme
  - Bump `func` dependency to 1.0.
  - dartfmt and small code changes for clarity when dealing with Func7+ (mapping numbers mentally to letters became more cumbersome for me at 7+ arguments from what I found, so I just made everything `argA` `argB` etc instead of `arg1` `arg2`).

### CODE REVIEW

**Comment by Aetet** [comment]
Hey, @brianegan . 

Thanks a lot for your pull request. It's nice to see a lot of tests and follow upstream.
Code is fine. That's an awesome job!

One thing left - could you fill changelog and bump minor version at pubspec.yaml? After that we can merge and publish this package at pub. Do you mind if after that we add you to readme as contributor?

**Comment by brianegan** [comment]
Thanks! 

Got the changelog, pubpsec, and readme updated with the latest commit. Let me know if I can do anything else :)

**Comment by Aetet** [comment]
@brianegan  Thanks to you. Package is published.

**Comment by brianegan** [comment]
Yay! Sounds great :D

**Pull request merged**
