### PR TITLE
Remove dependency on func package

### PR DESCRIPTION
**Pull request by ranquild**

### CODE REVIEW

**Comment by Aetet** [comment]
@brianegan Is this change ok with your library build and deps? Or we should roll out as major version?

**Comment by brianegan** [comment]
@aetet IMO: this is a breaking API change. 2.0.0 would be good to denote that and to follow semver.

**Comment by brianegan** [comment]
Looks like it could also break my love since it depends on a range up to 2.0.0, expecting Func1-10 back

**Comment by brianegan** [comment]
Break my library haha, sorry, in a phone

**Comment by ranquild** [comment]
Issues with Angular 3.1, does not worth it.

**Pull request closed without merging**
